spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  application:
    name: Hello Bitch for spring boot
    index: 1
    admin:
      enabled: true





